spring:
  cloud:
    gateway:
      routes:
        - id: dummy
          uri: lb://dummy
          predicates:
            - Path=/get

service:
  instances:
    dummy:
      uri: http://localhost:19999
      health_check_endpoint: /health
      fallback: http://localhost:29999

logging:
  level:
    com:
      example: DEBUG
    org:
      springframework:
        cloud:
          gateway:
            filter:
              LoadBalancerClientFilter: TRACE
        web:
          client:
            RestTemplate: DEBUG
server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management


